-- ============================================================
-- 1. Rename payment table
-- ============================================================

ALTER TABLE payment
    RENAME TO payments;


-- ============================================================
-- 2. Make payment.id identity-generated
-- ============================================================

ALTER TABLE payments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- ============================================================
-- 3. Make invoice_id mandatory
-- ============================================================

ALTER TABLE payments
    ALTER COLUMN invoice_id SET NOT NULL;


-- ============================================================
-- 4. Remove old join tables
--
-- Payment already has invoice_id, so these tables are
-- unnecessary with @OneToMany(mappedBy = "invoice").
-- ============================================================

DROP TABLE IF EXISTS invoice_payments;
DROP TABLE IF EXISTS invoices_payments_list;